/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vote;

import com.sun.jdi.connect.spi.Connection;
import java.awt.Image;
import java.sql.*;
import net.proteanit.sql.DbUtils;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sakib
 */
public class Voting extends javax.swing.JFrame {

    /**
     * Creates new form Voting
     */
    public Voting() {
        initComponents();
        DisplayCandidates();
        SuccessLbl.setVisible(false);
        
    }
    int VotingId;
    int ElecId;
    boolean f;
    public Voting(int VoterId,int Elec,boolean flg){
        initComponents();
        f=flg;
        VotingId=VoterId;
        ElecId=Elec;
        DisplayCandidates();
        
        SuccessLbl.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PresidentTbl = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        PhotoLbl = new javax.swing.JLabel();
        GsCastBtn = new javax.swing.JButton();
        Namelbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SuccessLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        VicePresidentAdTbl = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        VicePresidentOfTbl = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        GenSecretaryTbl = new javax.swing.JTable();
        PreCastBtn = new javax.swing.JButton();
        VP2CastBtn = new javax.swing.JButton();
        VP1CastBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setText("    Online Election System ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Welcome to Voting Arena ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Selected Candidate ");

        PresidentTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        PresidentTbl.setSelectionBackground(new java.awt.Color(0, 204, 204));
        PresidentTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PresidentTblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(PresidentTbl);

        jButton3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jButton3.setText("Logout");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        PhotoLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PhotoLbl.setForeground(new java.awt.Color(255, 51, 0));

        GsCastBtn.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        GsCastBtn.setText("Cast Vote");
        GsCastBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GsCastBtnMouseClicked(evt);
            }
        });
        GsCastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GsCastBtnActionPerformed(evt);
            }
        });

        Namelbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Namelbl.setForeground(new java.awt.Color(0, 204, 204));
        Namelbl.setText("Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("Vice_President(Office)");

        SuccessLbl.setFont(new java.awt.Font("Tahoma", 2, 22)); // NOI18N
        SuccessLbl.setForeground(new java.awt.Color(0, 204, 51));
        SuccessLbl.setText("Vote Counted Successfully!!");

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setText("President");

        VicePresidentAdTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        VicePresidentAdTbl.setSelectionBackground(new java.awt.Color(0, 204, 204));
        VicePresidentAdTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VicePresidentAdTblMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(VicePresidentAdTbl);

        VicePresidentOfTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        VicePresidentOfTbl.setSelectionBackground(new java.awt.Color(0, 204, 204));
        VicePresidentOfTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VicePresidentOfTblMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(VicePresidentOfTbl);

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setText("Vice_President");

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 204));
        jLabel9.setText("General Secretary");

        GenSecretaryTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        GenSecretaryTbl.setSelectionBackground(new java.awt.Color(0, 204, 204));
        GenSecretaryTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenSecretaryTblMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(GenSecretaryTbl);

        PreCastBtn.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        PreCastBtn.setText("Cast Vote");
        PreCastBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PreCastBtnMouseClicked(evt);
            }
        });
        PreCastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreCastBtnActionPerformed(evt);
            }
        });

        VP2CastBtn.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        VP2CastBtn.setText("Cast Vote");
        VP2CastBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VP2CastBtnMouseClicked(evt);
            }
        });
        VP2CastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VP2CastBtnActionPerformed(evt);
            }
        });

        VP1CastBtn.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        VP1CastBtn.setText("Cast Vote");
        VP1CastBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VP1CastBtnMouseClicked(evt);
            }
        });
        VP1CastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VP1CastBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(PhotoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(317, 317, 317)
                                .addComponent(SuccessLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(PreCastBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VP1CastBtn)
                .addGap(134, 134, 134)
                .addComponent(GsCastBtn)
                .addGap(150, 150, 150)
                .addComponent(VP2CastBtn)
                .addGap(83, 83, 83))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(395, 395, 395)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(SuccessLbl))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PhotoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Namelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VP1CastBtn)
                            .addComponent(VP2CastBtn)
                            .addComponent(GsCastBtn)
                            .addComponent(PreCastBtn))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    java.sql.Connection conn =null ;
    PreparedStatement pst =null;
    ResultSet Rs=null;
    Statement St=null;
    private void DisplayCandidates(){
        
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/electiondb","root","");
            St=conn.createStatement();
            Rs=St.executeQuery("Select CId, CName from CandidateTbl where Designation='President' and CElect="+ElecId+"");
            PresidentTbl.setModel(DbUtils.resultSetToTableModel(Rs));
            Rs=St.executeQuery("Select CId, CName from CandidateTbl where Designation='Vice-President(Admin)' and CElect="+ElecId+"");
            VicePresidentAdTbl.setModel(DbUtils.resultSetToTableModel(Rs));
            Rs=St.executeQuery("Select CId, CName from CandidateTbl where Designation='Vice-President(Office)' and CElect="+ElecId+"");
            VicePresidentOfTbl.setModel(DbUtils.resultSetToTableModel(Rs));
            Rs=St.executeQuery("Select CId, CName from CandidateTbl where Designation='General Secretary' and CElect="+ElecId+"");
            GenSecretaryTbl.setModel(DbUtils.resultSetToTableModel(Rs));
        }catch(Exception ex){
            
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void GsCastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GsCastBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GsCastBtnActionPerformed
    private void FetchPhoto(){
        String q="Select Cphoto from CandidateTbl where CId="+Key;
        Statement St;
        ResultSet Rs;
        
        try{
            Image img;
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/electiondb","root","");
            St=conn.createStatement();
            Rs=St.executeQuery(q);
            
            while(Rs.next()){
                photo=Rs.getBytes(1);
                img=getToolkit().createImage(photo);
                ImageIcon icon=new ImageIcon(img);
                PhotoLbl.setIcon(icon);
            }
        }
        catch(Exception ex){
            
        }
    }
    int Key=-1;
    
    private void PresidentTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PresidentTblMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel)PresidentTbl.getModel();
        int MyIndex=PresidentTbl.getSelectedRow();
        s="President";
        Key=Integer.valueOf(model.getValueAt(MyIndex,0).toString() );
        Namelbl.setText(model.getValueAt(MyIndex,1).toString());
       // ElecId=Integer.valueOf(model.getValueAt(MyIndex,4).toString() );
        FetchPhoto();
        SuccessLbl.setVisible(false);
        
    }//GEN-LAST:event_PresidentTblMouseClicked
    public static int VId;
Statement St1= null;
ResultSet Rs1=null;
    private void VCount() throws SQLException{
        St1=conn.createStatement();
        Rs1=St1.executeQuery("Select MAx(VoteId) from VotesTbl");

        Rs1.next();
        VId=Rs1.getInt(1)+1;
    }
    int VNumber;
    String s;
    private void VCheckGs(){
        try{
           
             St1=conn.createStatement();
            // Rs1.S1.executeQuery("Select *")
            
            
            Rs1=St1.executeQuery("Select * from VotesTbl Where VoterID="+VotingId+" and Designation='General Secretary'");
            //Rs1.next(); 
            //JOptionPane.showMessageDialog(this, Rs1);//problem ache .s
            
            VNumber=0;
            while(Rs1.next()){
                VNumber++;
            }
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
       
        
    }
    private void VCheckPre(){
        try{
           
             St1=conn.createStatement();
            // Rs1.S1.executeQuery("Select *")
            
            
            Rs1=St1.executeQuery("Select * from VotesTbl Where VoterID="+VotingId+" and Designation='President'");
            //Rs1.next(); 
            //JOptionPane.showMessageDialog(this, Rs1);//problem ache .s
            
            VNumber=0;
            while(Rs1.next()){
                VNumber++;
            }
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
       
        
    }
    private void VCheckVP1(){
        try{
           
             St1=conn.createStatement();
            // Rs1.S1.executeQuery("Select *")
            
            
            Rs1=St1.executeQuery("Select * from VotesTbl Where VoterID="+VotingId+" and Designation='Vice-President(Admin)'");
            //Rs1.next(); 
            //JOptionPane.showMessageDialog(this, Rs1);//problem ache .s
            
            VNumber=0;
            while(Rs1.next()){
                VNumber++;
            }
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
       
        
    }
    private void VCheckVP2(){
        try{
           
             St1=conn.createStatement();
            // Rs1.S1.executeQuery("Select *")
            
            
            Rs1=St1.executeQuery("Select * from VotesTbl Where VoterID="+VotingId+" and Designation='Vice-President(Office)'");
            //Rs1.next(); 
            //JOptionPane.showMessageDialog(this, Rs1);//problem ache .s
            
            VNumber=0;
            while(Rs1.next()){
                VNumber++;
            }
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
       
        
    }
    private void GsCastBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GsCastBtnMouseClicked
        // TODO add your handling code here:
        VCheckGs();
        
        if(Key==-1){
            JOptionPane.showMessageDialog(this, "Select Your Candidate.");
            
        }
        else if(VNumber>0){
            JOptionPane.showMessageDialog(this, "You can't Vote twice");
        }
        else{
            try{
               
               
               VCount();
               conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/electiondb","root","");
               PreparedStatement Add=conn.prepareStatement("insert into VotesTbl values(?,?,?,?,?)");
               
               Add.setInt(1,VId);
               Add.setInt(2,VotingId);
               Add.setInt(3,ElecId);
               Add.setInt(4,Key);
               Add.setString(5,"General Secretary" );
               int row =Add.executeUpdate();
              // JOptionPane.showMessageDialog(this,"Vote Counted");
               
               conn.close();
               SuccessLbl.setVisible(true);
               DisplayCandidates();
               GsCastBtn.setVisible(false);
               
               //DisplayElections();
               
               
             //  Add.SetInt(1,1);
               
               
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_GsCastBtnMouseClicked

    private void VicePresidentAdTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VicePresidentAdTblMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel)VicePresidentAdTbl.getModel();
        int MyIndex=VicePresidentAdTbl.getSelectedRow();
        Key=Integer.valueOf(model.getValueAt(MyIndex,0).toString() );
        s="Vice-President(Admin)";
        
        Namelbl.setText(model.getValueAt(MyIndex,1).toString());
       // ElecId=Integer.valueOf(model.getValueAt(MyIndex,4).toString() );
        FetchPhoto();
        SuccessLbl.setVisible(false);
    }//GEN-LAST:event_VicePresidentAdTblMouseClicked

    private void VicePresidentOfTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VicePresidentOfTblMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel)VicePresidentOfTbl.getModel();
        int MyIndex=VicePresidentOfTbl.getSelectedRow();
        s="Vice-President(Office)";
        Key=Integer.valueOf(model.getValueAt(MyIndex,0).toString() );
        Namelbl.setText(model.getValueAt(MyIndex,1).toString());
       // ElecId=Integer.valueOf(model.getValueAt(MyIndex,4).toString() );
        FetchPhoto();
        SuccessLbl.setVisible(false);
    }//GEN-LAST:event_VicePresidentOfTblMouseClicked

    private void GenSecretaryTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenSecretaryTblMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel)GenSecretaryTbl.getModel();
        int MyIndex=GenSecretaryTbl.getSelectedRow();
        s="General Secretary";
        Key=Integer.valueOf(model.getValueAt(MyIndex,0).toString() );
        Namelbl.setText(model.getValueAt(MyIndex,1).toString());
       // ElecId=Integer.valueOf(model.getValueAt(MyIndex,4).toString() );
        FetchPhoto();
        SuccessLbl.setVisible(false);
    }//GEN-LAST:event_GenSecretaryTblMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        new Login(f).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void PreCastBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PreCastBtnMouseClicked
        // TODO add your handling code here:
        VCheckPre(); /// Checks the voters to be countered second time or not .
        //System.out.println(VNumber);
        if(Key==-1){
            JOptionPane.showMessageDialog(this, "Select Your Candidate.");
            
        }
        else if(VNumber>0){
            JOptionPane.showMessageDialog(this, "You can't Vote twice");
        }
        else{
            try{
               
               
               VCount();
               conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/electiondb","root","");
               PreparedStatement Add=conn.prepareStatement("insert into VotesTbl values(?,?,?,?,?)");
               
               Add.setInt(1,VId);
               Add.setInt(2,VotingId);
               Add.setInt(3,ElecId);
               Add.setInt(4,Key);
               Add.setString(5,"President");
               int row =Add.executeUpdate();
              // JOptionPane.showMessageDialog(this,"Vote Counted");
               
               conn.close();
               SuccessLbl.setVisible(true);
               DisplayCandidates();
               PreCastBtn.setVisible(false);
               //PresidentTbl.setVisible(false);
               //DisplayElections();
               
               
             //  Add.SetInt(1,1);
               
               
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_PreCastBtnMouseClicked

    private void PreCastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreCastBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreCastBtnActionPerformed

    private void VP2CastBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VP2CastBtnMouseClicked
        // TODO add your handling code here:
        VCheckVP2();
       // System.out.println(VNumber);
        if(Key==-1){
            JOptionPane.showMessageDialog(this, "Select Your Candidate.");
            
        }
        else if(VNumber>0){
            JOptionPane.showMessageDialog(this, "You can't Vote twice");
        }
        else{
            try{
               
               
               VCount();
               conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/electiondb","root","");
               PreparedStatement Add=conn.prepareStatement("insert into VotesTbl values(?,?,?,?,?)");
               
               Add.setInt(1,VId);
               Add.setInt(2,VotingId);
               Add.setInt(3,ElecId);
               Add.setInt(4,Key);
               Add.setString(5,"Vice-President(Office)" );
               int row =Add.executeUpdate();
              // JOptionPane.showMessageDialog(this,"Vote Counted");
               
               conn.close();
               SuccessLbl.setVisible(true);
               DisplayCandidates();
               VP2CastBtn.setVisible(false);
               
               //DisplayElections();
               
               
             //  Add.SetInt(1,1);
               
               
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_VP2CastBtnMouseClicked

    private void VP2CastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VP2CastBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VP2CastBtnActionPerformed

    private void VP1CastBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VP1CastBtnMouseClicked
        // TODO add your handling code here:
        VCheckVP1();
        //System.out.println(VNumber);
        if(Key==-1){
            JOptionPane.showMessageDialog(this, "Select Your Candidate.");
            
        }
        else if(VNumber>0){
            JOptionPane.showMessageDialog(this, "You can't Vote twice");
        }
        else{
            try{
               
               
               VCount();
               conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/electiondb","root","");
               PreparedStatement Add=conn.prepareStatement("insert into VotesTbl values(?,?,?,?,?)");
               
               Add.setInt(1,VId);
               Add.setInt(2,VotingId);
               Add.setInt(3,ElecId);
               Add.setInt(4,Key);
               Add.setString(5,"Vice-President(Admin)" );
               int row =Add.executeUpdate();
              // JOptionPane.showMessageDialog(this,"Vote Counted");
               
               conn.close();
               SuccessLbl.setVisible(true);
               DisplayCandidates();
               VP1CastBtn.setVisible(false);
               
               //DisplayElections();
               
               
             //  Add.SetInt(1,1);
               
               
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_VP1CastBtnMouseClicked

    private void VP1CastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VP1CastBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VP1CastBtnActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        Namelbl.setText("");
        PhotoLbl.setIcon(null);
    }//GEN-LAST:event_jPanel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Voting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Voting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Voting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Voting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Voting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GenSecretaryTbl;
    private javax.swing.JButton GsCastBtn;
    private javax.swing.JLabel Namelbl;
    private javax.swing.JLabel PhotoLbl;
    private javax.swing.JButton PreCastBtn;
    private javax.swing.JTable PresidentTbl;
    private javax.swing.JLabel SuccessLbl;
    private javax.swing.JButton VP1CastBtn;
    private javax.swing.JButton VP2CastBtn;
    private javax.swing.JTable VicePresidentAdTbl;
    private javax.swing.JTable VicePresidentOfTbl;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
byte[]  photo =null;

}
